on:
  push:
    branches:
      - master
      - gnatutil
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: asis
      - uses: reznikmm/fedora-ada-action@v3
        with:
          spec: asis/asis.spec
      - name: Upload tar-ball to Bintray
        uses: reznikmm/upload-bintray-action@v3
        with:
          subject: reznikmm
          repository: matreshka
          package: asis
          version: head-fc33
          sourcePath: x86_64/*
          override: 1
          username: reznikmm
          apiKey: ${{secrets.BINTRAY_API_KEY}}